# Generated by Django 5.1.1 on 2024-10-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recurring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarentry",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A description of the calendar entry. Will be used as the ical summary",
            ),
        ),
        migrations.AlterField(
            model_name="calendarentry",
            name="name",
            field=models.CharField(
                default="",
                help_text="The name of the calendar entry. Will be used as the ical filename, slugified",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
