# Generated by Django 5.1.1 on 2024-10-01 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recurring", "0002_remove_recurrenceset_timezone_and_more"),
        ("testapp", "0002_remove_event_recurrence_set_event_calendar_entry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecurrenceSet",
        ),
        migrations.DeleteModel(
            name="RecurrenceSetRule",
        ),
    ]
