# Generated by Django 5.1.1 on 2024-10-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recurring", "0003_delete_recurrenceset_delete_recurrencesetrule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendarentry",
            options={"verbose_name_plural": "Calendar entries"},
        ),
        migrations.AlterField(
            model_name="event",
            name="recurrence_rule",
            field=models.OneToOneField(
                blank=True,
                help_text="The recurrence rule",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recurring.recurrencerule",
            ),
        ),
    ]
