# Generated by Django 5.1.1 on 2024-10-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recurring", "0004_alter_calendarentry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurrencerule",
            name="until",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time until which occurrences will be generated",
                null=True,
            ),
        ),
    ]
