# Generated by Django 5.1.1 on 2024-09-30 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recurring", "0005_recurrenceruledaterange_is_exclusion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurrencerule",
            name="until",
        ),
        migrations.AlterField(
            model_name="recurrencesetrule",
            name="recurrence_rule",
            field=models.OneToOneField(
                help_text="The recurrence rule",
                on_delete=django.db.models.deletion.CASCADE,
                to="recurring.recurrencerule",
            ),
        ),
    ]
